import sqlalchemy_utils.types
import sqlalchemy_utils
#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Nrp install revision."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'mbdb_spr_3'
down_revision = 'mbdb_spr_2'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mbdb_spr_file_draft_metadata_version_end_transaction_id', table_name='mbdb_spr_file_draft_metadata_version')
    op.drop_index('ix_mbdb_spr_file_draft_metadata_version_operation_type', table_name='mbdb_spr_file_draft_metadata_version')
    op.drop_index('ix_mbdb_spr_file_draft_metadata_version_transaction_id', table_name='mbdb_spr_file_draft_metadata_version')
    op.drop_table('mbdb_spr_file_draft_metadata_version')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mbdb_spr_file_draft_metadata_version',
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('record_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('object_version_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name='pk_mbdb_spr_file_draft_metadata_version')
    )
    op.create_index('ix_mbdb_spr_file_draft_metadata_version_transaction_id', 'mbdb_spr_file_draft_metadata_version', ['transaction_id'], unique=False)
    op.create_index('ix_mbdb_spr_file_draft_metadata_version_operation_type', 'mbdb_spr_file_draft_metadata_version', ['operation_type'], unique=False)
    op.create_index('ix_mbdb_spr_file_draft_metadata_version_end_transaction_id', 'mbdb_spr_file_draft_metadata_version', ['end_transaction_id'], unique=False)
    # ### end Alembic commands ###
