#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""migrate owners to access"""

import json

from alembic import op

# revision identifiers, used by Alembic.
revision = "mbdb_app_6"
down_revision = "mbdb_app_5"
branch_labels = ()
depends_on = None


affected_tables = [
    f"{model}{table}_metadata"
    for model in ("bli", "itc", "mst", "spr")
    for table in ("_draft", "")
]


def update_gp(table_name):
    conn = op.get_bind()
    for row in conn.execute("SELECT * FROM " + table_name):
        json_data = row["json"]
        if not json_data or "metadata" not in json_data:
            continue
        gp = json_data["metadata"]["general_parameters"]

        # update schema version
        gp["schema_version"] = "0.12.0"

        # replace technique field with method field
        method = gp["technique"]
        gp["method"] = method
        del gp["technique"]

        conn.execute(
            "UPDATE " + table_name + " SET json=%(js)s WHERE id=%(rowid)s",
            dict(js=json.dumps(json_data), rowid=row["id"]),
        )


def downgrade_gp(table_name):
    conn = op.get_bind()
    for row in conn.execute("SELECT * FROM " + table_name):
        json_data = row["json"]

        if not json_data or "metadata" not in json_data:
            continue

        gp = json_data["metadata"]["general_parameters"]

        # update schema version
        gp["schema_version"] = "0.11.0"

        # replace method field with technique field
        technique = gp["method"]
        gp["technique"] = technique
        del gp["method"]

        conn.execute(
            "UPDATE " + table_name + " SET json=%(js)s WHERE id=%(rowid)s",
            dict(js=json.dumps(json_data), rowid=row["id"]),
        )


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in affected_tables:
        update_gp(table)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in affected_tables:
        downgrade_gp(table)
    # ### end Alembic commands ###
