#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""rdm fix"""

from alembic import op
import json

# revision identifiers, used by Alembic.
revision = "mbdb_app_8"
down_revision = "mbdb_app_7"
branch_labels = ()
depends_on = None


affected_tables = [
    f"{model}{table}_metadata"
    for model in ("spr", "bli", "itc", "mst")
    for table in ("_draft", "")
]


def update_records(table_name):
    conn = op.get_bind()
    for row in conn.execute("SELECT * FROM " + table_name):
        json_data = row["json"]
        json_data.update({
            "custom_fields": {},
            "pids": {},
            "media_files": {
                "enabled": False,
            },
            "access":{
                "files": "public",
                "record": "public",
                "embargo":{
                    "active": False,
                    "reason": None,
                    "until": None,
                },
            },
        })

        conn.execute(
            "UPDATE " + table_name + " SET json=%(js)s WHERE id=%(rowid)s",
            dict(js=json.dumps(json_data), rowid=row["id"]),
        )


def downgrade_records(table_name):
    conn = op.get_bind()
    for row in conn.execute("SELECT * FROM " + table_name):
        json_data = row["json"]

        for rdm_field in ("custom_fields", "media_files", "access", "pids"):
            del json_data[rdm_field]

        conn.execute(
            "UPDATE " + table_name + " SET json=%(js)s WHERE id=%(rowid)s",
            dict(js=json.dumps(json_data), rowid=row["id"]),
        )

def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in affected_tables:
        update_records(table)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in affected_tables:
        downgrade_records(table)
    # ### end Alembic commands ###
