#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

import json

from alembic import op

# revision identifiers, used by Alembic.
revision = "mbdb_app_11"
down_revision = "mbdb_app_10"
branch_labels = ()
depends_on = None

AFFECTED_METHODS = ("spr", "mst", "bli", "itc", "mp")
GP_SCHEMA_VERSION = "0.15.0"

def tables_constructor(method):
    return [f"{method}_metadata", f"{method}_draft_metadata"]

def get_upgrade_msp_schema_version(method):
    if method == "spr":
        return "0.10.2"
    if method == "mst":
        return "0.9.12"
    if method == "bli":
        return "0.9.9"
    if method == "itc":
        return "0.1.1"
    if method == "mp":
        return "1.0.1"
    raise ValueError(f"Unsupported method: {method}")

def get_downgrade_msp_schema_version(method):
    if method == "spr":
        return "0.10.2"
    if method == "mst":
        return "0.9.11"
    if method == "bli":
        return "0.9.8"
    if method == "itc":
        return "0.1.0"
    if method == "mp":
        return "1.0.0"
    raise ValueError(f"Unsupported method: {method}")


def get_upgrade_gp_schema_version():
    return "0.15.0"

def get_downgrade_gp_schema_version():
    return "0.14.2"


def set_schema_version(table_name, gp_version, msp_version):
    conn = op.get_bind()

    for row in conn.execute("SELECT * FROM " + table_name):
        json_data = row["json"]
        if not json_data or "metadata" not in json_data:
            continue

        metadata = json_data["metadata"]
        gp = metadata.get("general_parameters")
        msp = metadata.get("method_specific_parameters")

        if not gp or not msp:
            continue

        gp["schema_version"] = gp_version
        msp["schema_version"] = msp_version

        conn.execute(
            "UPDATE " + table_name + " SET json=%(js)s WHERE id=%(rowid)s",
            {"js": json.dumps(json_data), "rowid": row["id"]},
        )

def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    gp_version = get_upgrade_gp_schema_version()

    for method in AFFECTED_METHODS:
        msp_version = get_upgrade_msp_schema_version(method)
        for table in tables_constructor(method):
            set_schema_version(table, gp_version, msp_version)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    gp_version = get_downgrade_gp_schema_version()

    for method in AFFECTED_METHODS:
        msp_version = get_downgrade_msp_schema_version(method)
        for table in tables_constructor(method):
            set_schema_version(table, gp_version, msp_version)
    # ### end Alembic commands ###
