#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""spr flow rate"""

import json

from alembic import op

# revision identifiers, used by Alembic.
revision = "mbdb_app_7"
down_revision = "mbdb_app_6"
branch_labels = ()
depends_on = None


affected_tables = [
    f"{model}{table}_metadata" for model in ("spr",) for table in ("_draft", "")
]


def update_spr(table_name):
    conn = op.get_bind()
    for row in conn.execute("SELECT * FROM " + table_name):
        json_data = row["json"]
        if not json_data or "metadata" not in json_data:
            continue
        msp = json_data["metadata"]["method_specific_parameters"]

        # update schema version
        msp["schema_version"] = "0.10.0"

        # unify rate by converting from
        # flow:
        #   rate: float
        #   unit: str
        # to
        # flow:
        #   rate:
        #     value: float
        #     unit: str

        measurement_protocol = msp.get("measurement_protocol", [])
        for step in measurement_protocol:
            flow = step.get("flow")
            if not flow:
                continue
            rate = {}
            if "rate" in flow:
                rate["value"] = flow["rate"]
            if "unit":
                rate["unit"] = flow["unit"]
                del flow["unit"]
            if rate:
                flow["rate"] = rate

        conn.execute(
            "UPDATE " + table_name + " SET json=%(js)s WHERE id=%(rowid)s",
            dict(js=json.dumps(json_data), rowid=row["id"]),
        )


def downgrade_spr(table_name):
    conn = op.get_bind()
    for row in conn.execute("SELECT * FROM " + table_name):
        json_data = row["json"]
        if not json_data or "metadata" not in json_data:
            continue

        msp = json_data["metadata"]["method_specific_parameters"]

        # update schema version
        msp["schema_version"] = "0.9.7"

        # convert from
        # flow:
        #   rate:
        #     value: float
        #     unit: str
        # flow:
        #   rate: float
        #   unit: str

        measurement_protocol = msp.get("measurement_protocol", [])
        for step in measurement_protocol:
            flow = step.get("flow", {})
            rate = flow.get("rate", {})
            if not flow and rate:
                continue
            if "value" in rate:
                rate["rate"] = rate["value"]
                del rate["value"]
            flow.update(rate)

        conn.execute(
            "UPDATE " + table_name + " SET json=%(js)s WHERE id=%(rowid)s",
            dict(js=json.dumps(json_data), rowid=row["id"]),
        )


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in affected_tables:
        update_spr(table)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in affected_tables:
        downgrade_spr(table)
    # ### end Alembic commands ###
