import sqlalchemy_utils.types
import sqlalchemy_utils
#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Nrp install revision."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'mbdb_app_4'
down_revision = 'mbdb_app_3'
branch_labels = ()
depends_on = None

def _set_deletion_status(model):
    metadata_table = sa.sql.table(
        f"{model}_metadata", sa.sql.column("deletion_status")
    )
    metadata_version_table = sa.sql.table(
        f"{model}_metadata_version", sa.sql.column("deletion_status")
    )
    op.execute(metadata_table.update().values(deletion_status="P"))
    op.execute(metadata_version_table.update().values(deletion_status="P"))
    op.alter_column(f"{model}_metadata", "deletion_status", nullable=False)

def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rdm_parents_metadata',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rdm_parents_metadata'))
    )
    op.create_table('rdm_records_access_request_tokens',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('record_pid', sa.String(length=255), nullable=False),
    sa.Column('consent_to_share_personal_data', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rdm_records_access_request_tokens'))
    )
    op.create_index(op.f('ix_rdm_records_access_request_tokens_created'), 'rdm_records_access_request_tokens', ['created'], unique=False)
    op.create_table('rdm_records_files_version',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), autoincrement=False, nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), autoincrement=False, nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), autoincrement=False, nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_rdm_records_files_version'))
    )
    op.create_index(op.f('ix_rdm_records_files_version_end_transaction_id'), 'rdm_records_files_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_rdm_records_files_version_object_version_id'), 'rdm_records_files_version', ['object_version_id'], unique=False)
    op.create_index(op.f('ix_rdm_records_files_version_operation_type'), 'rdm_records_files_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_rdm_records_files_version_record_id'), 'rdm_records_files_version', ['record_id'], unique=False)
    op.create_index(op.f('ix_rdm_records_files_version_transaction_id'), 'rdm_records_files_version', ['transaction_id'], unique=False)
    op.create_table('rdm_records_media_files_version',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), autoincrement=False, nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), autoincrement=False, nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), autoincrement=False, nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_rdm_records_media_files_version'))
    )
    op.create_index(op.f('ix_rdm_records_media_files_version_end_transaction_id'), 'rdm_records_media_files_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_rdm_records_media_files_version_object_version_id'), 'rdm_records_media_files_version', ['object_version_id'], unique=False)
    op.create_index(op.f('ix_rdm_records_media_files_version_operation_type'), 'rdm_records_media_files_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_rdm_records_media_files_version_record_id'), 'rdm_records_media_files_version', ['record_id'], unique=False)
    op.create_index(op.f('ix_rdm_records_media_files_version_transaction_id'), 'rdm_records_media_files_version', ['transaction_id'], unique=False)
    op.create_table('rdm_records_metadata_version',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), autoincrement=False, nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), autoincrement=False, nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('index', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_rdm_records_metadata_version'))
    )
    op.create_index(op.f('ix_rdm_records_metadata_version_bucket_id'), 'rdm_records_metadata_version', ['bucket_id'], unique=False)
    op.create_index(op.f('ix_rdm_records_metadata_version_end_transaction_id'), 'rdm_records_metadata_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_rdm_records_metadata_version_media_bucket_id'), 'rdm_records_metadata_version', ['media_bucket_id'], unique=False)
    op.create_index(op.f('ix_rdm_records_metadata_version_operation_type'), 'rdm_records_metadata_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_rdm_records_metadata_version_transaction_id'), 'rdm_records_metadata_version', ['transaction_id'], unique=False)
    op.create_table('rdm_records_secret_links',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('permission_level', sa.String(), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rdm_records_secret_links'))
    )
    op.create_index(op.f('ix_rdm_records_secret_links_created'), 'rdm_records_secret_links', ['created'], unique=False)
    op.create_table('rdm_records_quota',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quota_size', sa.BigInteger(), nullable=False),
    sa.Column('max_file_size', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['rdm_parents_metadata.id'], name=op.f('fk_rdm_records_quota_parent_id_rdm_parents_metadata'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rdm_records_quota')),
    sa.UniqueConstraint('parent_id', name=op.f('uq_rdm_records_quota_parent_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_rdm_records_quota_user_id'))
    )
    op.create_table('rdm_users_quota',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('quota_size', sa.BigInteger(), nullable=False),
    sa.Column('max_file_size', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], name=op.f('fk_rdm_users_quota_user_id_accounts_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rdm_users_quota')),
    sa.UniqueConstraint('user_id', name=op.f('uq_rdm_users_quota_user_id'))
    )
    op.create_table('rdm_drafts_metadata',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('fork_version_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_rdm_drafts_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_rdm_drafts_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['rdm_parents_metadata.id'], name=op.f('fk_rdm_drafts_metadata_parent_id_rdm_parents_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rdm_drafts_metadata'))
    )
    op.create_index(op.f('ix_rdm_drafts_metadata_bucket_id'), 'rdm_drafts_metadata', ['bucket_id'], unique=False)
    op.create_index(op.f('ix_rdm_drafts_metadata_media_bucket_id'), 'rdm_drafts_metadata', ['media_bucket_id'], unique=False)
    op.create_table('rdm_records_metadata',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_rdm_records_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_rdm_records_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['rdm_parents_metadata.id'], name=op.f('fk_rdm_records_metadata_parent_id_rdm_parents_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rdm_records_metadata'))
    )
    op.create_index(op.f('ix_rdm_records_metadata_bucket_id'), 'rdm_records_metadata', ['bucket_id'], unique=False)
    op.create_index(op.f('ix_rdm_records_metadata_media_bucket_id'), 'rdm_records_metadata', ['media_bucket_id'], unique=False)
    op.create_table('rdm_drafts_files',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_rdm_drafts_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['rdm_drafts_metadata.id'], name=op.f('fk_rdm_drafts_files_record_id_rdm_drafts_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rdm_drafts_files'))
    )
    op.create_index(op.f('ix_rdm_drafts_files_object_version_id'), 'rdm_drafts_files', ['object_version_id'], unique=False)
    op.create_index(op.f('ix_rdm_drafts_files_record_id'), 'rdm_drafts_files', ['record_id'], unique=False)
    op.create_index('uidx_rdm_drafts_files_record_id_key', 'rdm_drafts_files', ['record_id', 'key'], unique=True)
    op.create_table('rdm_drafts_media_files',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_rdm_drafts_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['rdm_drafts_metadata.id'], name=op.f('fk_rdm_drafts_media_files_record_id_rdm_drafts_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rdm_drafts_media_files'))
    )
    op.create_index(op.f('ix_rdm_drafts_media_files_object_version_id'), 'rdm_drafts_media_files', ['object_version_id'], unique=False)
    op.create_index(op.f('ix_rdm_drafts_media_files_record_id'), 'rdm_drafts_media_files', ['record_id'], unique=False)
    op.create_index('uidx_rdm_drafts_media_files_record_id_key', 'rdm_drafts_media_files', ['record_id', 'key'], unique=True)
    op.create_table('rdm_parents_community',
    sa.Column('community_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('request_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities_metadata.id'], name=op.f('fk_rdm_parents_community_community_id_communities_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['rdm_parents_metadata.id'], name=op.f('fk_rdm_parents_community_record_id_rdm_parents_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['request_metadata.id'], name=op.f('fk_rdm_parents_community_request_id_request_metadata'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('community_id', 'record_id', name=op.f('pk_rdm_parents_community'))
    )
    op.create_table('rdm_records_files',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_rdm_records_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['rdm_records_metadata.id'], name=op.f('fk_rdm_records_files_record_id_rdm_records_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rdm_records_files'))
    )
    op.create_index(op.f('ix_rdm_records_files_object_version_id'), 'rdm_records_files', ['object_version_id'], unique=False)
    op.create_index(op.f('ix_rdm_records_files_record_id'), 'rdm_records_files', ['record_id'], unique=False)
    op.create_index('uidx_rdm_records_files_record_id_key', 'rdm_records_files', ['record_id', 'key'], unique=True)
    op.create_table('rdm_records_media_files',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_rdm_records_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['rdm_records_metadata.id'], name=op.f('fk_rdm_records_media_files_record_id_rdm_records_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rdm_records_media_files'))
    )
    op.create_index(op.f('ix_rdm_records_media_files_object_version_id'), 'rdm_records_media_files', ['object_version_id'], unique=False)
    op.create_index(op.f('ix_rdm_records_media_files_record_id'), 'rdm_records_media_files', ['record_id'], unique=False)
    op.create_index('uidx_rdm_records_media_files_record_id_key', 'rdm_records_media_files', ['record_id', 'key'], unique=True)
    op.create_table('rdm_versions_state',
    sa.Column('latest_index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('latest_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('next_draft_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['latest_id'], ['rdm_records_metadata.id'], name=op.f('fk_rdm_versions_state_latest_id_rdm_records_metadata')),
    sa.ForeignKeyConstraint(['next_draft_id'], ['rdm_drafts_metadata.id'], name=op.f('fk_rdm_versions_state_next_draft_id_rdm_drafts_metadata')),
    sa.ForeignKeyConstraint(['parent_id'], ['rdm_parents_metadata.id'], name=op.f('fk_rdm_versions_state_parent_id_rdm_parents_metadata'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', name=op.f('pk_rdm_versions_state'))
    )
    op.add_column('bli_draft_metadata', sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True))
    op.add_column('bli_draft_metadata', sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_index(op.f('ix_bli_draft_metadata_media_bucket_id'), 'bli_draft_metadata', ['media_bucket_id'], unique=False)
    op.create_foreign_key(op.f('fk_bli_draft_metadata_media_bucket_id_files_bucket'), 'bli_draft_metadata', 'files_bucket', ['media_bucket_id'], ['id'])
    op.add_column('bli_metadata', sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True))
    op.add_column('bli_metadata', sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_index(op.f('ix_bli_metadata_media_bucket_id'), 'bli_metadata', ['media_bucket_id'], unique=False)
    op.create_foreign_key(op.f('fk_bli_metadata_media_bucket_id_files_bucket'), 'bli_metadata', 'files_bucket', ['media_bucket_id'], ['id'])
    op.add_column('bli_metadata_version', sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True))
    op.add_column('bli_metadata_version', sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_bli_metadata_version_media_bucket_id'), 'bli_metadata_version', ['media_bucket_id'], unique=False)
    op.drop_index('ix_uq_partial_files_object_is_head', table_name='files_object')
    op.add_column('itc_draft_metadata', sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True))
    op.add_column('itc_draft_metadata', sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_index(op.f('ix_itc_draft_metadata_media_bucket_id'), 'itc_draft_metadata', ['media_bucket_id'], unique=False)
    op.create_foreign_key(op.f('fk_itc_draft_metadata_media_bucket_id_files_bucket'), 'itc_draft_metadata', 'files_bucket', ['media_bucket_id'], ['id'])
    op.add_column('itc_metadata', sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True))
    op.add_column('itc_metadata', sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_index(op.f('ix_itc_metadata_media_bucket_id'), 'itc_metadata', ['media_bucket_id'], unique=False)
    op.create_foreign_key(op.f('fk_itc_metadata_media_bucket_id_files_bucket'), 'itc_metadata', 'files_bucket', ['media_bucket_id'], ['id'])
    op.add_column('itc_metadata_version', sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True))
    op.add_column('itc_metadata_version', sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_itc_metadata_version_media_bucket_id'), 'itc_metadata_version', ['media_bucket_id'], unique=False)
    op.add_column('mst_draft_metadata', sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True))
    op.add_column('mst_draft_metadata', sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_index(op.f('ix_mst_draft_metadata_media_bucket_id'), 'mst_draft_metadata', ['media_bucket_id'], unique=False)
    op.create_foreign_key(op.f('fk_mst_draft_metadata_media_bucket_id_files_bucket'), 'mst_draft_metadata', 'files_bucket', ['media_bucket_id'], ['id'])
    op.add_column('mst_metadata', sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True))
    op.add_column('mst_metadata', sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_index(op.f('ix_mst_metadata_media_bucket_id'), 'mst_metadata', ['media_bucket_id'], unique=False)
    op.create_foreign_key(op.f('fk_mst_metadata_media_bucket_id_files_bucket'), 'mst_metadata', 'files_bucket', ['media_bucket_id'], ['id'])
    op.add_column('mst_metadata_version', sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True))
    op.add_column('mst_metadata_version', sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_mst_metadata_version_media_bucket_id'), 'mst_metadata_version', ['media_bucket_id'], unique=False)
    op.add_column('spr_draft_metadata', sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True))
    op.add_column('spr_draft_metadata', sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_index(op.f('ix_spr_draft_metadata_media_bucket_id'), 'spr_draft_metadata', ['media_bucket_id'], unique=False)
    op.create_foreign_key(op.f('fk_spr_draft_metadata_media_bucket_id_files_bucket'), 'spr_draft_metadata', 'files_bucket', ['media_bucket_id'], ['id'])
    op.add_column('spr_metadata', sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True))
    op.add_column('spr_metadata', sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_index(op.f('ix_spr_metadata_media_bucket_id'), 'spr_metadata', ['media_bucket_id'], unique=False)
    op.create_foreign_key(op.f('fk_spr_metadata_media_bucket_id_files_bucket'), 'spr_metadata', 'files_bucket', ['media_bucket_id'], ['id'])
    op.add_column('spr_metadata_version', sa.Column('deletion_status', sa.String(1), autoincrement=False, nullable=True))
    op.add_column('spr_metadata_version', sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_spr_metadata_version_media_bucket_id'), 'spr_metadata_version', ['media_bucket_id'], unique=False)
    # ### end Alembic commands ###
    for model in ("mst", "bli", "itc", "spr"):
        _set_deletion_status(model=model)


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spr_metadata_version_media_bucket_id'), table_name='spr_metadata_version')
    op.drop_column('spr_metadata_version', 'media_bucket_id')
    op.drop_column('spr_metadata_version', 'deletion_status')
    op.drop_constraint(op.f('fk_spr_metadata_media_bucket_id_files_bucket'), 'spr_metadata', type_='foreignkey')
    op.drop_index(op.f('ix_spr_metadata_media_bucket_id'), table_name='spr_metadata')
    op.drop_column('spr_metadata', 'media_bucket_id')
    op.drop_column('spr_metadata', 'deletion_status')
    op.drop_constraint(op.f('fk_spr_draft_metadata_media_bucket_id_files_bucket'), 'spr_draft_metadata', type_='foreignkey')
    op.drop_index(op.f('ix_spr_draft_metadata_media_bucket_id'), table_name='spr_draft_metadata')
    op.drop_column('spr_draft_metadata', 'media_bucket_id')
    op.drop_column('spr_draft_metadata', 'deletion_status')
    op.drop_index(op.f('ix_mst_metadata_version_media_bucket_id'), table_name='mst_metadata_version')
    op.drop_column('mst_metadata_version', 'media_bucket_id')
    op.drop_column('mst_metadata_version', 'deletion_status')
    op.drop_constraint(op.f('fk_mst_metadata_media_bucket_id_files_bucket'), 'mst_metadata', type_='foreignkey')
    op.drop_index(op.f('ix_mst_metadata_media_bucket_id'), table_name='mst_metadata')
    op.drop_column('mst_metadata', 'media_bucket_id')
    op.drop_column('mst_metadata', 'deletion_status')
    op.drop_constraint(op.f('fk_mst_draft_metadata_media_bucket_id_files_bucket'), 'mst_draft_metadata', type_='foreignkey')
    op.drop_index(op.f('ix_mst_draft_metadata_media_bucket_id'), table_name='mst_draft_metadata')
    op.drop_column('mst_draft_metadata', 'media_bucket_id')
    op.drop_column('mst_draft_metadata', 'deletion_status')
    op.drop_index(op.f('ix_itc_metadata_version_media_bucket_id'), table_name='itc_metadata_version')
    op.drop_column('itc_metadata_version', 'media_bucket_id')
    op.drop_column('itc_metadata_version', 'deletion_status')
    op.drop_constraint(op.f('fk_itc_metadata_media_bucket_id_files_bucket'), 'itc_metadata', type_='foreignkey')
    op.drop_index(op.f('ix_itc_metadata_media_bucket_id'), table_name='itc_metadata')
    op.drop_column('itc_metadata', 'media_bucket_id')
    op.drop_column('itc_metadata', 'deletion_status')
    op.drop_constraint(op.f('fk_itc_draft_metadata_media_bucket_id_files_bucket'), 'itc_draft_metadata', type_='foreignkey')
    op.drop_index(op.f('ix_itc_draft_metadata_media_bucket_id'), table_name='itc_draft_metadata')
    op.drop_column('itc_draft_metadata', 'media_bucket_id')
    op.drop_column('itc_draft_metadata', 'deletion_status')
    op.create_index('ix_uq_partial_files_object_is_head', 'files_object', ['bucket_id', 'key'], unique=False)
    op.drop_index(op.f('ix_bli_metadata_version_media_bucket_id'), table_name='bli_metadata_version')
    op.drop_column('bli_metadata_version', 'media_bucket_id')
    op.drop_column('bli_metadata_version', 'deletion_status')
    op.drop_constraint(op.f('fk_bli_metadata_media_bucket_id_files_bucket'), 'bli_metadata', type_='foreignkey')
    op.drop_index(op.f('ix_bli_metadata_media_bucket_id'), table_name='bli_metadata')
    op.drop_column('bli_metadata', 'media_bucket_id')
    op.drop_column('bli_metadata', 'deletion_status')
    op.drop_constraint(op.f('fk_bli_draft_metadata_media_bucket_id_files_bucket'), 'bli_draft_metadata', type_='foreignkey')
    op.drop_index(op.f('ix_bli_draft_metadata_media_bucket_id'), table_name='bli_draft_metadata')
    op.drop_column('bli_draft_metadata', 'media_bucket_id')
    op.drop_column('bli_draft_metadata', 'deletion_status')
    op.drop_table('rdm_versions_state')
    op.drop_index('uidx_rdm_records_media_files_record_id_key', table_name='rdm_records_media_files')
    op.drop_index(op.f('ix_rdm_records_media_files_record_id'), table_name='rdm_records_media_files')
    op.drop_index(op.f('ix_rdm_records_media_files_object_version_id'), table_name='rdm_records_media_files')
    op.drop_table('rdm_records_media_files')
    op.drop_index('uidx_rdm_records_files_record_id_key', table_name='rdm_records_files')
    op.drop_index(op.f('ix_rdm_records_files_record_id'), table_name='rdm_records_files')
    op.drop_index(op.f('ix_rdm_records_files_object_version_id'), table_name='rdm_records_files')
    op.drop_table('rdm_records_files')
    op.drop_table('rdm_parents_community')
    op.drop_index('uidx_rdm_drafts_media_files_record_id_key', table_name='rdm_drafts_media_files')
    op.drop_index(op.f('ix_rdm_drafts_media_files_record_id'), table_name='rdm_drafts_media_files')
    op.drop_index(op.f('ix_rdm_drafts_media_files_object_version_id'), table_name='rdm_drafts_media_files')
    op.drop_table('rdm_drafts_media_files')
    op.drop_index('uidx_rdm_drafts_files_record_id_key', table_name='rdm_drafts_files')
    op.drop_index(op.f('ix_rdm_drafts_files_record_id'), table_name='rdm_drafts_files')
    op.drop_index(op.f('ix_rdm_drafts_files_object_version_id'), table_name='rdm_drafts_files')
    op.drop_table('rdm_drafts_files')
    op.drop_index(op.f('ix_rdm_records_metadata_media_bucket_id'), table_name='rdm_records_metadata')
    op.drop_index(op.f('ix_rdm_records_metadata_bucket_id'), table_name='rdm_records_metadata')
    op.drop_table('rdm_records_metadata')
    op.drop_index(op.f('ix_rdm_drafts_metadata_media_bucket_id'), table_name='rdm_drafts_metadata')
    op.drop_index(op.f('ix_rdm_drafts_metadata_bucket_id'), table_name='rdm_drafts_metadata')
    op.drop_table('rdm_drafts_metadata')
    op.drop_table('rdm_users_quota')
    op.drop_table('rdm_records_quota')
    op.drop_index(op.f('ix_rdm_records_secret_links_created'), table_name='rdm_records_secret_links')
    op.drop_table('rdm_records_secret_links')
    op.drop_index(op.f('ix_rdm_records_metadata_version_transaction_id'), table_name='rdm_records_metadata_version')
    op.drop_index(op.f('ix_rdm_records_metadata_version_operation_type'), table_name='rdm_records_metadata_version')
    op.drop_index(op.f('ix_rdm_records_metadata_version_media_bucket_id'), table_name='rdm_records_metadata_version')
    op.drop_index(op.f('ix_rdm_records_metadata_version_end_transaction_id'), table_name='rdm_records_metadata_version')
    op.drop_index(op.f('ix_rdm_records_metadata_version_bucket_id'), table_name='rdm_records_metadata_version')
    op.drop_table('rdm_records_metadata_version')
    op.drop_index(op.f('ix_rdm_records_media_files_version_transaction_id'), table_name='rdm_records_media_files_version')
    op.drop_index(op.f('ix_rdm_records_media_files_version_record_id'), table_name='rdm_records_media_files_version')
    op.drop_index(op.f('ix_rdm_records_media_files_version_operation_type'), table_name='rdm_records_media_files_version')
    op.drop_index(op.f('ix_rdm_records_media_files_version_object_version_id'), table_name='rdm_records_media_files_version')
    op.drop_index(op.f('ix_rdm_records_media_files_version_end_transaction_id'), table_name='rdm_records_media_files_version')
    op.drop_table('rdm_records_media_files_version')
    op.drop_index(op.f('ix_rdm_records_files_version_transaction_id'), table_name='rdm_records_files_version')
    op.drop_index(op.f('ix_rdm_records_files_version_record_id'), table_name='rdm_records_files_version')
    op.drop_index(op.f('ix_rdm_records_files_version_operation_type'), table_name='rdm_records_files_version')
    op.drop_index(op.f('ix_rdm_records_files_version_object_version_id'), table_name='rdm_records_files_version')
    op.drop_index(op.f('ix_rdm_records_files_version_end_transaction_id'), table_name='rdm_records_files_version')
    op.drop_table('rdm_records_files_version')
    op.drop_index(op.f('ix_rdm_records_access_request_tokens_created'), table_name='rdm_records_access_request_tokens')
    op.drop_table('rdm_records_access_request_tokens')
    op.drop_table('rdm_parents_metadata')
    # ### end Alembic commands ###
