#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""general parameters updated to accommodate mp model"""

import json

from alembic import op

# revision identifiers, used by Alembic.
revision = "mbdb_app_9"
down_revision = "mbdb_app_8"
branch_labels = ()
depends_on = None


affected_tables = [
    f"{model}{table}_metadata"
    for model in ("spr", "bli", "itc", "mst")
    for table in ("_draft", "")
]


def update_records(table_name):
    conn = op.get_bind()
    for row in conn.execute("SELECT * FROM " + table_name):
        json_data = row["json"]
        if not json_data or "metadata" not in json_data:
            continue
        gp = json_data["metadata"].setdefault("general_parameters", {})

        # update schema version
        gp["schema_version"] = "0.13.0"

        conn.execute(
            "UPDATE " + table_name + " SET json=%(js)s WHERE id=%(rowid)s",
            dict(js=json.dumps(json_data), rowid=row["id"]),
        )


def downgrade_records(table_name):
    conn = op.get_bind()
    for row in conn.execute("SELECT * FROM " + table_name):
        json_data = row["json"]
        if not json_data or "metadata" not in json_data:
            continue
        gp = json_data["metadata"].setdefault("general_parameters", {})

        # update schema version
        gp["schema_version"] = "0.12.0"

        conn.execute(
            "UPDATE " + table_name + " SET json=%(js)s WHERE id=%(rowid)s",
            dict(js=json.dumps(json_data), rowid=row["id"]),
        )


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in affected_tables:
        update_records(table)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in affected_tables:
        downgrade_records(table)
    # ### end Alembic commands ###
