#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""migrate owners to access"""

from alembic import op
import json

# revision identifiers, used by Alembic.
revision = "mbdb_app_5"
down_revision = "mbdb_app_4"
branch_labels = ()
depends_on = None


def migrate_to_rdm_owners(table_name):
    conn = op.get_bind()
    for row in conn.execute("SELECT * FROM " + table_name):
        json_data = row["json"]
        if "owners" not in json_data:
            print("Do not have owner in record", row["id"], table_name)
            continue
        if len(json_data["owners"]) != 1:
            print(
                f"Multiple owners in record in {table_name}",
                row["id"],
                json_data["owners"],
            )
            owner = max(owner["user"] for owner in json_data["owners"])
        else:
            owner = json_data["owners"][0]["user"]

        json_data["access"] = {
            "links": [],
            "grants": [],
            "owned_by": {"user": owner},
            "settings": {
                "allow_user_requests": True,
                "allow_guest_requests": True,
                "accept_conditions_text": None,
                "secret_link_expiration": 0,
            },
        }
        del json_data["owners"]

        conn.execute(
            "UPDATE " + table_name + " SET json=%(js)s WHERE id=%(rowid)s",
            dict(js=json.dumps(json_data), rowid=row["id"]),
        )


def migrate_to_oarepo_owners(table_name):
    conn = op.get_bind()
    for row in conn.execute("SELECT * FROM " + table_name):
        json_data = row["json"]
        owner = json_data["access"].get("owned_by")
        if not owner:
            print("Do not have owner in record", row["id"], table_name)
            continue

        json_data["owners"] = [owner]
        del json_data["access"]

        conn.execute(
            "UPDATE " + table_name + " SET json=%(js)s WHERE id=%(rowid)s",
            dict(js=json.dumps(json_data), rowid=row["id"]),
        )


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    migrate_to_rdm_owners("mst_parent_record_metadata")
    migrate_to_rdm_owners("bli_parent_record_metadata")
    migrate_to_rdm_owners("itc_parent_record_metadata")
    migrate_to_rdm_owners("spr_parent_record_metadata")
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    migrate_to_oarepo_owners("mst_parent_record_metadata")
    migrate_to_oarepo_owners("bli_parent_record_metadata")
    migrate_to_oarepo_owners("itc_parent_record_metadata")
    migrate_to_oarepo_owners("spr_parent_record_metadata")
    # ### end Alembic commands ###
