#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Initial revision."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '413ae05aa1e1'
down_revision = 'mbdb_mst_file_1'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mbdbmst_metadata_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('mbdbmst_metadata_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('mbdbmst_metadata_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('mbdbmstfile_metadata_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('mbdbmstfile_metadata_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('mbdbmstfile_metadata_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('mbdbmstfile_metadata_version', 'key',
               existing_type=sa.TEXT(),
               nullable=True,
               autoincrement=False)
    op.alter_column('mbdbmstfile_metadata_version', 'record_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mbdbmstfile_metadata_version', 'record_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               autoincrement=False)
    op.alter_column('mbdbmstfile_metadata_version', 'key',
               existing_type=sa.TEXT(),
               nullable=False,
               autoincrement=False)
    op.alter_column('mbdbmstfile_metadata_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('mbdbmstfile_metadata_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('mbdbmstfile_metadata_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('mbdbmst_metadata_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('mbdbmst_metadata_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('mbdbmst_metadata_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
