author_email: Emildandanell.agerschou@ibt.cas.cz
author_name: Emil Dandanell Agerschou
installation_site: mbdb-site
merge_changes: overwrite
model_dir: models/mbdb-bli
model_kind: empty
model_package: mbdb_bli
permissions_preset: everyone
permissions_presets: read_only
pid_type: bli
run_tests: skip
sites:
- mbdb-site
update_opensearch: run
use_custom_fields: 'yes'
use_docs: 'no'
use_drafts: 'no'
use_expandable_fields: 'no'
use_files: 'yes'
use_metadata: 'no'
use_nr_vocabularies: 'no'
use_relations: 'yes'
use_requests: 'no'
use_tests: 'no'
use_vocabularies: 'yes'
