name: Build and test

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (11, 12, ...)
        required: true
        default: 12
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INVENIO_SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:postgres@localhost:5432/mbdb
      INVENIO_OPENSEARCH_PORT: "9200"
      INVENIO_REDIS_PORT: "6379"
      INVENIO_CELERY_BROKER_URL: "redis://localhost:6379/0"
      INVENIO_BROKER_URL: "redis://localhost:6379/0"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Cache pip
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - uses: actions/setup-node@v3
        with:
          # Version Spec of the version to use in SemVer notation.
          # It also emits such aliases as lts, latest, nightly and canary builds
          # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
          node-version: '16.x'

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Opensearch
        uses: ankane/setup-opensearch@v1
        with:
          plugins: analysis-icu
          opensearch-version: 2.15.0

      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Install uv
        run: |
            pip install uv

      - name: Run tests
        run: |
          ./tests/build_test.sh

      - name: Freeze packages
        run: |
          .venv/bin/pip freeze > requirements.txt

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: requirements.txt
          path: requirements.txt
