record:
  mapping:
    template:
      settings:
        index.mapping.total_fields.limit: 3000
        index.mapping.nested_fields.limit: 200
        index.query.default_field: collected_default_search_fields
