record:
  mapping:
    template:
      settings:
        index.mapping.total_fields.limit: 3000
        index.mapping.nested_fields.limit: 200
        index.query.default_field:
          - collected_default_search_fields
          - collected_default_search_fields.substringmatch
        analysis:
          analyzer:
            substring:
              tokenizer: substringtokenizer
          "tokenizer":
            "substringtokenizer":
              "type": "ngram"
              "min_gram": 3
              "max_gram": 3
              "token_chars":
                - "letter"
                - "digit"

  properties:
    collected_default_search_fields:
      type: fulltext
      marshmallow:
        read: false
        write: false
      mapping:
          fields:
            substringmatch:
              type: text
              analyzer: substring
    id:
      type: keyword
      mapping:
        copy_to: collected_default_search_fields
  service-config:
    components: ["{{oarepo_vocabularies.authorities.components.AuthorityComponent}}"]
  search-options:
    base-classes: [common.services.records.search_options.RecordSearchOptions]
